### ISSUE TITLE
Clean SSH Exit

### ISSUE THREAD

**Issue by afalami** [afourmy/eNMS#153]
Hi 
eNMS version 3.14.7,

i'm using NetmikoBackupService to backup a Cisco ASA in multiple contexts mode. 
The script makes ssh connection to the same devices as many times as there are contexts. 
Cisco ASA is limited to 5 concurrent SSH connections. The 5 first contexts are backuped correctly but all the other contexts failed. 
It looks like the script doesn't close properly the ssh session. 
This issue is not present in previous versions of eNMS

Great tool. 
Regard,

**Comment by afourmy** [comment]
Hi,

Thanks for letting me know, it should be fixed in the latest release, eNMS 3.15.

**Comment by afalami** [comment]
Hi, thanx for your reply. 

I've tested 3.15 and still have the issue. 

Regard,

**Comment by afourmy** [comment]
Just released 3.17, can you try again now ?
I refactored the configuration management system.
Note that in case you're using multiprocessing, you should be using a database capable of handling multiple concurrent commits such as PostgreSQL or MySQL, otherwise a service may fail in the middle, which can lead to netmiko/napalm connection to a device being left open until they time out.
Thanks
