### ISSUE TITLE
Resize Map

### ISSUE THREAD

**Issue by KillerRyuk** [afourmy/eNMS#34]
Resize map - on 2k screen the map only utilizes half of the screen.  It would be nice for it to automatically fill the screen (good for on-going display purposes).    
![enmsmap](https://user-images.githubusercontent.com/35462044/34952008-cc2d82f4-f9dd-11e7-86ac-139e633ba027.PNG)

**Comment by afourmy** [comment]
Hello @KillerRyuk,

I made a change that should fix this problem... but I don't have a screen that big, only a very small one, so I'm not 100% sure that it's actually fixed.
Can you clone the project (current master branch) and see if this is better now ?

Also, for the other issue you raised about being able to edit an object, this should be fixed for **nodes** (I will fix it for links later). You can edit an object either by importing a new Excel file with the updates you need, or by recreating the object (if you create an object with a name that already exists, it will actually be updated). 

In the future, the editing of an object will have to be done with an editable datatable that sends a AJAX request each time the user modifies a property, that would be a better solution.

**Comment by KillerRyuk** [comment]
After re-running the clone, I still get the same map size.  Monitor for reference is a 28" @2560x1440

**Comment by afourmy** [comment]
Hello @KillerRyuk ,

You said you re-ran the clone, but did you re-clone before ? It seems to me that you don't have the latest changes (even if it doesn't work, the size should not be exactly the same).

To be sure, can you check the file _/eNMS/source/views/template/geographical_view.html **line 9**_ ?
You should have `#mapid { height:90vh; }`. 
If you don't, you don't have the latest changes and you should re-clone eNMS (download the latest version on github)

Thanks

**Comment by KillerRyuk** [comment]
I ran the git clone again and it still didn't take the changes.  I manually changed the map to the 90vh and it is working now.  Thanks.

**Comment by afourmy** [comment]
Ok then I can close this. I think the reason why you didn't have the latest changes is that you did not re-clone the project from github (`git clone https://github.com/afourmy/eNMS.git` in the git console)
